backend:                                                                                        
  name: github                                                                                  
  repo: Act2Antiques/act-ii-antiques-                                                           
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["order", "title"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number", default: 10 }
      - { label: "Era", name: "era", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Additional Details", name: "details", widget: "text", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string" }
      - { label: "Material", name: "material", widget: "string" }
      - { label: "Condition", name: "condition", widget: "string" }                             
      - { label: "Price", name: "price", widget: "string" }

  - name: "pages"
    label: "Pages"
    files:
      - label: "About Page"
        name: "about"
        file: "_content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Intro", name: "intro", widget: "text" }
          - { label: "Story Title", name: "story_title", widget: "string" }
          - { label: "Story Text", name: "story", widget: "text" }
