backend:
  name: github
  repo: Act2Antiques/act-ii-antiques-
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "_products"
    create: true
    slug: "{{slug}}"
    sortable_fields: ["order", "title"]
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Order", name: "order", widget: "number", default: 10 }
      - { label: "Era", name: "era", widget: "string" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Additional Details", name: "details", widget: "text", required: false }
      - { label: "Dimensions", name: "dimensions", widget: "string" }
      - { label: "Material", name: "material", widget: "string" }
      - { label: "Condition", name: "condition", widget: "string" }
      - { label: "Price", name: "price", widget: "string" }
      - { label: "Sold", name: "sold", widget: "boolean", default: false }

  - name: "pages"
    label: "Pages"
    files:
      - label: "Homepage"
        name: "homepage"
        file: "_content/homepage.md"
        fields:
          - { label: "Collection Heading", name: "collection_heading", widget: "string" }
          - { label: "About Heading", name: "about_heading", widget: "string" }
          - { label: "About Paragraph 1", name: "about_text_1", widget: "text" }
          - { label: "About Paragraph 2", name: "about_text_2", widget: "text" }
          - { label: "About Button Text", name: "about_button", widget: "string" }
          - { label: "About Image", name: "about_image", widget: "image" }
      - label: "About Page"
        name: "about"
        file: "_content/about.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Paragraph 1", name: "paragraph_1", widget: "text" }
          - { label: "Paragraph 2", name: "paragraph_2", widget: "text" }
          - { label: "Paragraph 3", name: "paragraph_3", widget: "text" }
          - { label: "About Image", name: "about_image", widget: "image" }
      - label: "Contact Page"
        name: "contact"
        file: "_content/contact.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Contact Note", name: "contact_note", widget: "text" }
